Module8 task1
htmlacademy-javascript/2483435-kekstagram-31 pull request #10
Opened 2024-03-10 12:34 UTC by b-trots

Вопрос:
В файле **thumbnails.js** на 22 строчке я заношу коллекцию дочерних изображений контейнера, по которым планирую кликать, в переменную:

const **targetThumbnails** = container.querySelectorAll('.picture__img');

Я хотел вынести эту константу в начало и заменить ее на выражение:

const **targetThumbnails** = container.children.filter((item) => item.classList.contains('picture'));

И я не понимаю, почему она не работает.

2024-03-10 18:29 UTC, baileys-li requested changes

2024-03-10 18:29 UTC, baileys-li commented on js/thumbnails.js
>  const createThumbnails = createDescriptionImages();
```suggestion
const createdThumbnails = createDescriptionImages();
```

2024-03-10 18:29 UTC, baileys-li commented on js/thumbnails.js
> +for (let i = 0; i < targetThumbnails.length; i++){
зачем навешиваешь обработчик клика в отдельном цикле?

2024-03-10 18:29 UTC, baileys-li commented on js/showFullPhoto.js
> +  bigPhotoModal.querySelector('.big-picture__img').firstElementChild.src = url;
Можно так искать
```suggestion
  bigPhotoModal.querySelector('.big-picture__img img').src = url;
```

2024-03-10 18:29 UTC, baileys-li commented on js/showFullPhoto.js
> +  bigPhotoModal.querySelector('.social__comment-shown-count').textContent = '';
А почему пустая?

2024-03-10 18:29 UTC, baileys-li commented on js/showFullPhoto.js
> +  closeModalButton.addEventListener('click', () => closeModal());
А зачем вешаешь безымянную функцию на каждое открытие?

2024-03-10 18:33 UTC, baileys-li commented
> const targetThumbnails = container.children.filter((item) => item.classList.contains('picture'));
HTML коллекция это не массив, у неё нет такого метода

Но вообще тебе оно не надо

2024-03-11 09:07 UTC, b-trots commented on js/thumbnails.js
> +for (let i = 0; i < targetThumbnails.length; i++){
Я не понимаю, как без **targetThumbnails** отправить объект кликнутой картинки в отрисовку

2024-03-11 09:10 UTC, b-trots commented on js/showFullPhoto.js
> +  closeModalButton.addEventListener('click', () => closeModal());
Не понимаю вопроса
**hideBlocks();** - скрывает окна по заданию.
**blockScrolling();** - запрещает скролл страницы при открытом фото.
**closeModalButton.addEventListener('click', () => closeModal());** - при открытом окне ждёт нажатия на крестик, чтобы закрыть окно.

2024-03-11 09:25 UTC, b-trots commented on js/thumbnails.js
> +for (let i = 0; i < targetThumbnails.length; i++){
Разобрался. Убрал лишний цикл.

2024-03-11 09:30 UTC, b-trots commented on js/showFullPhoto.js
> +  closeModalButton.addEventListener('click', () => closeModal());
Понял. Убрал.

2024-03-11 10:30 UTC, baileys-li approved these changes

2024-03-11 10:30 UTC, baileys-li commented on js/thumbnails.js
> +const createdThumbnails = createDescriptionImages();
Ты скорее данные фотографий создаёшь, а не миниатюры. Миниатюры это вьюха, отображение

2024-03-11 10:30 UTC, baileys-li commented on js/showFullPhoto.js
> +  closeModalButton.addEventListener('click', closeModal);
Так и не понял зачем ты переподписываешь на каждое открытие?

2024-03-11 10:31 UTC, baileys-li commented
> Co-authored-by: Богдан Троценко <trotsbv@gmail.com>
Co-authored-by: Богдан Троценко <email>

Что-то пошло не так

2024-03-11 10:31 UTC, merged

2024-03-11 12:46 UTC, b-trots commented on js/showFullPhoto.js
> +  closeModalButton.addEventListener('click', closeModal);
Не понимаю вопроса. 
Можно на созвон оставить