Больше деталей
htmlacademy-javascript/2483435-kekstagram-31 pull request #4
Opened 2024-02-25 12:47 UTC by b-trots

2024-02-26 11:41 UTC, baileys-li requested changes
Поправь ESlint ошибки в предыдущем файле

2024-02-26 11:41 UTC, baileys-li commented on js/main.js
> +  comments: generateComments(Math.floor(Math.random() * 31))
У тебя же есть функция на рандомное число

2024-02-26 11:41 UTC, baileys-li commented on js/main.js
> +      avatar: String(`img/avatar-${getRandomInteger(1,6)}.svg`),
Это и так строка
```suggestion
      avatar: `img/avatar-${getRandomInteger(1,6)}.svg`,
```

2024-02-26 11:41 UTC, baileys-li commented on js/main.js
> +const generateMessage = (value, storageMessage) => {
Можно короче, на звонке покажу

2024-02-26 11:41 UTC, baileys-li commented on js/main.js
> +  return function() {
Напомнимаю про критерий про стрелки

2024-02-26 11:41 UTC, baileys-li commented on js/main.js
> +const getValueProperty = (min, max, uniqueness = 0) => {
Почему `uniqueness` число а не булевый. Если ты его юзаешь как булевый тип

2024-02-26 11:41 UTC, baileys-li commented on js/main.js
> +const getValueProperty = (min, max, uniqueness = 0) => {
```suggestion
const createIdGenerator= (min, max, uniqueness = false) => {
```

2024-02-26 11:41 UTC, baileys-li commented on js/main.js
> +const idComments = getValueProperty(1,1000, true);
Глаголы
```suggestion
const getCommentId = getValueProperty(1,1000, true);
```

2024-02-27 10:56 UTC, bvtrots commented on js/main.js
> +const getValueProperty = (min, max, uniqueness = 0) => {
Не понял, зачем менять имя генератора? Мы же не только Id через эту функцию прогоняем, но и url, description, getCommentId

2024-02-28 13:03 UTC, baileys-li approved these changes

2024-02-28 13:06 UTC, merged