Функции возвращаются
htmlacademy-javascript/2483435-kekstagram-31 pull request #6
Opened 2024-02-28 21:08 UTC by b-trots

2024-02-28 21:31 UTC, b-trots commented
Мне не понятно, почему он показывает, что я изменил весь файл functions.js
Хотя я только функцию последнюю добавил, а все остальное в комментарий занес

2024-02-29 07:54 UTC, baileys-li commented
> Мне не понятно, почему он показывает, что я изменил весь файл functions.js Хотя я только функцию последнюю добавил, а все остальное в комментарий занес

Ты закомментировал другие строчки. Он смотрит на разницу между коммитами

2024-02-29 07:55 UTC, baileys-li requested changes

2024-02-29 07:55 UTC, baileys-li commented on index.html
> +script src="./js/functions.js"></script>
Удали эту штуку

2024-02-29 07:55 UTC, baileys-li commented on index.html
> +script src="./js/functions.js"></script>
И порешай конфликты в этом файле

2024-03-01 16:17 UTC, bvtrots commented
Я действительно запутался во всех этих махинациях...
Но вроде всё сделал.

2024-03-01 18:09 UTC, merged